#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

curl -fL -o ${DOWNLOADS}/orig.tar.gz ${KERNEL_ORIG_URL}
curl -fL -o ${DOWNLOADS}/diff.gz ${KERNEL_DIFF_URL}

# construct kernel source
mkdir -p build/kernel
pushd ${DOWNLOADS}
tar xf orig.tar.gz
gunzip diff.gz
popd

pushd build/kernel
mv ${DOWNLOADS}/linux-*/* build/kernel
patch -p1 -i ${DOWNLOADS}/*.diff
popd

# custom patches
PATCHES_DIR=$(pwd)/patches
pushd build/kernel
for p in `find ${PATCHES_DIR} -name "*.patch"`; do
    echo "patching $p"
    patch -p1 -i $p
done
popd

