#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

#
# Currently only package the aws artifacts
#

AWS_HEADERS_DIR=dist/aws/headers
AWS_MAIN_DIR=dist/aws/main
AWS_EXTRA_DIR=dist/aws/modules-extra

mkdir -p ${AWS_HEADERS_DIR} ${AWS_MAIN_DIR} ${AWS_EXTRA_DIR}

KERNEL_BASE_DIR=build/kernel/debian

# headers
cp -rf ${KERNEL_BASE_DIR}/linux-headers-*-aws/usr ${AWS_HEADERS_DIR}
cp -rf ${KERNEL_BASE_DIR}/linux-headers-*-aws/lib ${AWS_HEADERS_DIR}

# main modules and vmlinuz
IMAGE_AWS_DIR=${KERNEL_BASE_DIR}/linux-image-unsigned-*-aws
if [ ! -d ${IMAGE_AWS_DIR} ]; then
    IMAGE_AWS_DIR=${KERNEL_BASE_DIR}/linux-image-*-aws
fi
cp -rf ${IMAGE_AWS_DIR}/boot ${AWS_MAIN_DIR}
cp -rf ${KERNEL_BASE_DIR}/linux-modules-*-aws/boot ${AWS_MAIN_DIR}
cp -rf ${KERNEL_BASE_DIR}/linux-modules-*-aws/lib ${AWS_MAIN_DIR}

# extra modules
cp -rf ${KERNEL_BASE_DIR}/linux-modules-extra-*-aws/lib ${AWS_EXTRA_DIR}

# package artifacts
mkdir -p dist/artifacts

pushd ${AWS_HEADERS_DIR}
tar cvJf ../../artifacts/kernel-headers-aws_${ARCH}.tar.xz .
popd

pushd ${AWS_MAIN_DIR}
tar cvJf ../../artifacts/kernel-aws_${ARCH}.tar.xz .
popd

pushd ${AWS_EXTRA_DIR}
tar cvJf ../../artifacts/kernel-extra-aws_${ARCH}.tar.xz .
popd
